version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: payment
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  payment-service:
    build: ./payment-service
    restart: on-failure
    environment:
      - MERCADOPAGO_ACCESS_TOKEN=${MERCADOPAGO_ACCESS_TOKEN}
      - MONGO_URI=mongodb://mongo:27017/payment
      - NOTIFICATION_URL=${NOTIFICATION_URL}
      - BACKEND_URL=${BACKEND_URL}
    ports:
      - "4000:4000"
    depends_on:
      - mongo

volumes:
  mongo_data:
